export default {
  translateX: ({ x })  => `translateX(${[x].join(' ')})`,
  translateY: ({ y })  => `translateY(${[y].join(' ')})`,
  translate: ({ x, y })  => `translate(${[x, y].join(' ')})`,
  translateZ: ({ z })  => `translateZ(${[z].join(' ')})`,
  translate3d: ({ x, y, z })  => `translate3d(${[x, y, z].join(' ')})`,
  scaleX: ({ x })  => `scaleX(${[x].join(' ')})`,
  scaleY: ({ y })  => `scaleY(${[y].join(' ')})`,
  scale: ({ x, y })  => `scale(${[x, y].join(' ')})`,
  scaleZ: ({ z })  => `scaleZ(${[z].join(' ')})`,
  scale3d: ({ x, y, z })  => `scale3d(${[x, y, z].join(' ')})`,
  rotateX: ({ a })  => `rotateX(${[a].join(' ')})`,
  rotateY: ({ a })  => `rotateY(${[a].join(' ')})`,
  rotate: ({ a })  => `rotate(${[a].join(' ')})`,
  rotateZ: ({ z })  => `rotateZ(${[z].join(' ')})`,
  rotate3d: ({ x, y, z, a })  => `rotate3d(${[x, y, z, a].join(' ')})`,
  skewX: (ax)  => `skewX(${[ax].join(' ')})`,
  skewY: (ay)  => `skewY(${[ay].join(' ')})`,
  skew: ({ ax, ay })  => `skew(${[ax, ay].join(' ')})`,
  matrix: ({ a, b, c, d, tx, ty })  => `matrix(${[a, b, c, d, tx, ty].join(' ')})`,
  matrix3d: ({ a1, b1, c1, d1, a2, b2, c2, d2, a3, b3, c3, d3, a4, b4, c4, d4 })  => `matrix3d(${[a1, b1, c1, d1, a2, b2, c2, d2, a3, b3, c3, d3, a4, b4, c4, d4].join(' ')})`,
  perspective: ({ d })  => `perspective(${[d].join(' ')})`,
}
